#!/bin/sh
module="pxs50.ko"
device="SWPci-Xs50-"
group="root"
mode="777"
major="254"

#invoke insmod with all arguments we got
insmod -f $module 

#remove stale nodes
rm -f /dev/${device}[0-7]

major=`cat /proc/devices | awk -F " " '$2=="SWPci-Xs50" {print $1}'`

mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
mknod /dev/${device}4 c $major 4
mknod /dev/${device}5 c $major 5
mknod /dev/${device}6 c $major 6
mknod /dev/${device}7 c $major 7

#give appropriate group/permissions
#chgrp $group /dev/$device*
chmod $mode /dev/$device*



